---
version: "3.3"
services:

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    labels:
      description: Prometheus exporter to monitor system metrics
      url: http://caprica.fritz.box:9100
    restart: always
    command:
      - --path.rootfs=/host
    pid: host
    network_mode: host
    volumes:
      - /:/host:ro,rslave
      - /etc/timezone:/etc/timezone:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    labels:
      description: Prometheus exporter to monitor docker containers
      url: http://caprica.fritz.box:9110
    restart: always
    expose:
      - 9110
    ports:
      - 9110:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    labels:
      description: Manage docker containers
      url: http://caprica.fritz.box:9990
    command: -H unix:///var/run/docker.sock --admin-password-file /tmp/portainer_passwords
    restart: always
    ports:
      - 9990:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./assets/portainer.passwd:/tmp/portainer_passwords
      - /etc/timezone:/etc/timezone:ro

volumes:
  portainer_data:
