= API Docs: Bash Scripts
Jenkins Pipeline <sebastian@sommerfeld.io>

The full package documentation for all bash scripts of this project. All scripts are written for the link:https://en.wikipedia.org/wiki/Bash_(Unix_shell)[Bash] shell.

All scripts expect certain variables to be present. These variables are all in conjunction with coloring the console output. To use the variables, simply add these lines to your users .bashrc file.

[source, bash]
----
export LOG_DONE="[\e[32mDONE\e[0m]"
export LOG_ERROR="[\e[1;31mERROR\e[0m]"
export LOG_INFO="[\e[34mINFO\e[0m]"
export LOG_WARN="[\e[93mWARN\e[0m]"

export Y="\e[93m" # yellow
export P="\e[35m" # pink
export D="\e[0m"  # default (= white)
----

== Bash Scripts
// From this point down: generated content only ...

* xref:src_main_clean.adoc[src/main/clean.sh]
* xref:src_main_kube-cluster_deploy_dashboard.adoc[src/main/kube-cluster/deploy/dashboard.sh]
* xref:src_main_kube-cluster_deploy_metrics-server.adoc[src/main/kube-cluster/deploy/metrics-server.sh]
* xref:src_main_kube-cluster_kubernetes-setup_bash-setup.adoc[src/main/kube-cluster/kubernetes-setup/bash-setup.sh]
* xref:src_main_kube-deploy.adoc[src/main/kube-deploy.sh]
* xref:src_main_kube-proxy-on.adoc[src/main/kube-proxy-on.sh]
* xref:src_main_start.adoc[src/main/start.sh]
* xref:src_main_stop.adoc[src/main/stop.sh]
* xref:src_main_vagrant-ssh.adoc[src/main/vagrant-ssh.sh]
* xref:src_main_vars.adoc[src/main/vars.sh]
